### ISSUE TITLE
Undefined variable oldStyleParams

### ISSUE THREAD

**Issue by tomhughes** [Firefishy/SimpleMap#2]
Not sure if it's another deprecation or what but there are warnings about oldStyleParams:

```
PHP Notice:  Undefined variable: oldStyleParams in /srv/wiki.openstreetmap.org/w/extensions/SimpleMap/SimpleMap.class.php on line 99
```

**Comment by Firefishy** [comment]
It seems to be an remnant from old code @harry-wood cleared out in 249fb4fa00805ec6ea88454625516495d71331a9

**Comment by harry-wood** [comment]
oh yeah. I must've missed a bit when dropping the oldStyleParams stuff
